# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190427_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='writer',
            field=models.CharField(max_length=200),
        ),
    ]
