# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20190427_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
