# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190427_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ML', 'Major/Lan'), ('WD', 'Work/Dev'), ('H', 'Hob')], default='', max_length=10),
        ),
    ]
