# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190427_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Major/Language', '\uc804\uacf5/\uc5b8\uc5b4'), ('Work/Development', '\uc2e4\ubb34/\uac1c\ubc1c'), ('Hobby', '\ucde8\ubbf8')], default='Major/Language', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Major/Language', '\uc804\uacf5/\uc5b8\uc5b4'), ('Work/Development', '\uc2e4\ubb34/\uac1c\ubc1c'), ('Hobby', '\ucde8\ubbf8')], default='Major/Language', max_length=100),
        ),
    ]
