# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
