# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190428_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tutor_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
