# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_tutor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tutor_num',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
