# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190428_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ref_url',
            field=models.URLField(default=''),
        ),
    ]
