# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_ref_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ref_url',
        ),
    ]
